name = "minikube"
type = "cli"

[platform.linux]
download-file = "minikube-linux-{arch}"
bin-path = "minikube"
checksum-file = "{download_file}.sha256"

[platform.macos]
download-file = "minikube-darwin-{arch}"
bin-path = "minikube"
checksum-file = "{download_file}.sha256"

[platform.windows]
download-file = "minikube-windows-{arch}.exe"
bin-path = "minikube.exe"
checksum-file = "{download_file}.sha256"

[install]
download-url = "https://storage.googleapis.com/minikube/releases/v{version}/{download_file}"
checksum-url = "https://storage.googleapis.com/minikube/releases/v{version}/{checksum_file}"
unpack = false

[install.arch]
aarch64 = "arm64"
arm = "arm"
x86 = "386"
x86_64 = "amd64"
