name = "skaffold"
type = "cli"

[platform.linux]
download-file = "skaffold-linux-{arch}"
bin-path = "skaffold"
checksum-file = "skaffold-linux-{arch}.sha256"

[platform.macos]
download-file = "skaffold-darwin-{arch}"
bin-path = "skaffold"
checksum-file = "skaffold-darwin-{arch}.sha256"

[platform.windows]
download-file = "skaffold-windows-{arch}.exe"
bin-path = "skaffold.exe"
checksum-file = "skaffold-windows-{arch}.sha256"

[install]
download-url = "https://storage.googleapis.com/skaffold/releases/v{version}/{download_file}"
checksum-url = "https://storage.googleapis.com/skaffold/releases/v{version}/{checksum_file}"
unpack = false

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/GoogleContainerTools/skaffold"
